services:
    nginx-unit:
        container_name: shop_nginx_unit
        build:
            context: .
            dockerfile: docker/nginx-unit/Dockerfile
        ports:
            - "80:80"
            - "8080:8080"
        volumes:
            - ./:/var/www/html
        working_dir: /var/www/html
        depends_on:
            - mysql
        networks:
            - app-network

    mysql:
        container_name: shop_mysql
        image: "mysql:8"
        ports:
            - "3306:3306"
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            # MYSQL_USER: ${DB_USERNAME}
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./docker/database/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
